infra/concourse/Makefile.BUILD
infra/concourse/build/Dockerfile.kitchen-terraform

This package is necessary to facilitate SSH proxy connections.

Add openssh to Kitchen-Terraform image

---

dm/templates/instance/instance.py.schema
dm/templates/instance_template/instance_template.py.schema
dm/templates/managed_instance_group/managed_instance_group.py.schema

Schema naming for `natIP` and `networkIP` were incorrectly named `natIp` and `networkIp`.
Not an issue with the actual API requests, however having a matching schema makes it a lot easier to troubleshoot the problem.

Resolved issues with instance schema naming not aligned with api

---

dm/templates/instance/examples/instance.yaml
dm/templates/instance/tests/integration/instance.bats

Removed declaration of diskSizeGb to have disk size default to image size and not post a warning message.
Added missing # to comment in bats file to allow test execution

Fix for Warming message in instance example

---

dm/templates/project/project.py.schema

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/32
project/project.py: networkAccess in groups and serviceAccounts must be
false if sharedVPC is disabled
https://github.com/GoogleCloudPlatform/deploymentmanager-samples/issues/242
Missing non mandatory parameter makes deployment fail - project factory

Fixes project.py schema

---

infra/terraform/test_fixtures/main.tf

This change is necessary to maintain compatibilty with the newer
releases of Project Factory.

Pin Google providers to 2.7.0

---

dm/templates/gcs_bucket/gcs_bucket.py.schema

https://cloud.google.com/storage/docs/access-logs
> Optionally, you can set the log_object_prefix object prefix for your log objects. The object prefix forms the beginning of the log object name. It can be at most 900 characters and must be a valid object name. By default, the object prefix is the name of the bucket for which the logs are enabled.
The default is fairly sane and not all users will want to override it.

Don't require logObjectPrefix for buckets

---

dm/templates/cloud_router/cloud_router.py
dm/templates/cloud_router/cloud_router.py.schema
dm/templates/cloud_router/tests/schemas/invalid_additional_options.yaml
dm/templates/cloud_router/tests/schemas/valid_basic.yaml

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/51
- Added support for "description"
- Added missing fields:
- bgp (only asn is supported now)
- nats
- bgpPeers
- interfaces
- Added basic schema unit tests

Fixes #51: DM/cloud_router: refactoring

---

dm/templates/gcs_bucket/gcs_bucket.py
dm/templates/gcs_bucket/gcs_bucket.py.schema

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/66
- Added uniqueItems: true to lists
- Added additionalProperties: false for nested object
- Fixed "bindings" schema
- Added support for "requesterPays"
- Added support for "acl", "billing", "cors", "defaultEventBasedHold", "defaultObjectAcl", "encryption", "iamConfiguration", "retentionPolicy"

Fixes #66: DM/gcs_bucket: refactoring

---

dm/templates/network/network.py
dm/templates/network/network.py.schema
dm/templates/network/subnetwork.py
dm/templates/network/subnetwork.py.schema
dm/templates/network/tests/schemas/invalid_subnets.yaml
dm/templates/network/tests/schemas/valid_auto.yaml
dm/templates/network/tests/schemas/valid_subnets.yaml

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/56
- Added support for cross-project resource creation (both network and
subnetwork)
- Added oneOf check for subnets: autoCreateSubnetworks should be exclusive
with subnet list
- Fixed network & subnetworks resources names
- Added support for "description", "routingConfig" to network
- Fixed "secondaryIpRanges" definition in subnetwork
- Added basic schema unit tests

Fixes #56: DM/network: refactoring

---

dm/templates/cloud_sql/cloud_sql.py
dm/templates/cloud_sql/cloud_sql.py.schema
dm/templates/cloud_sql/tests/schemas/invalid_additional_options.yaml
dm/templates/cloud_sql/tests/schemas/invalid_additional_options_nested.yaml
dm/templates/cloud_sql/tests/schemas/invalid_missing_region.yaml
dm/templates/cloud_sql/tests/schemas/invalid_missing_tier.yaml
dm/templates/cloud_sql/tests/schemas/valid_basic.yaml
dm/templates/cloud_sql/tests/schemas/valid_complex.yaml

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/54
- Added enum for "databaseVersion", "region", "settings.pricingPlan",
"settings.replicationType"
- Added additionalProperties: false for nested object
- Fixed "users" schema
- Added basic schemas unit tests

Fixes #54: DM/cloud_sql: refactoring

---

dm/templates/cloud_spanner/cloud_spanner.py
dm/templates/cloud_spanner/cloud_spanner.py.schema
dm/templates/cloud_spanner/tests/schemas/invalid_additional_options.yaml
dm/templates/cloud_spanner/tests/schemas/valid_basic.yaml
dm/templates/cloud_spanner/tests/schemas/valid_complex.yaml

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/53
- Added support for "labels"
- Made "name" optional, correctly handle it
- Updated "instanceConfig" enum with new values
- Added basic schema unit tests
- Added additionalProperties: false for nested objects

Fixes #53: DM/cloud_spanner: refactoring

---

dm/templates/instance/examples/instance.yaml
dm/templates/instance/instance.py
dm/templates/instance/instance.py.schema

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/70
- Added additionalProperties: false for nested objects
- Added support for "description", "networkInterfaces[].accessConfigs[]",
"networkInterfaces[].aliasIpRanges[]", "disks", "scheduling", "labels",
"minCpuPlatform", "guestAccelerators", "deletionProtection", "hostname",
"shieldedInstanceConfig", "shieldedInstanceIntegrityPolicy":
[docs](https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert)

Fixes #70: DM/instance: refactoring

---

infra/terraform/test_fixtures/terraform-google-forseti.tf

This patch fixes the error `google_compute_instance.main: Error loading machine type: googleapi: Error 403: Required 'compute.machineTypes.get' permission for 'projects/ci-forseti-host-6f38/zones/us-central1-f/machineTypes/f1-micro', forbidden`.

Add compute.instanceAdmin.v1 for host project

---

dm/templates/folder/folder.py
dm/templates/folder/folder.py.schema

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/55
- added version, links to docs
- fixed folder resource names: use base resource name as a template
- added oneOf check for folderId/orgId + fix incorrect schema for array
- fixed "displayName" regex
- made "name" field optional
- using the same format for parent as in project + fixed name prefix to
plural

Fixes #55: DM/folder: refactoring

---

dm/templates/instance_template/examples/instance_template.yaml
dm/templates/instance_template/instance_template.py
dm/templates/instance_template/instance_template.py.schema
dm/templates/instance_template/tests/integration/instance_template.bats
dm/templates/instance_template/tests/integration/instance_template.yaml
dm/templates/instance_template/tests/integration/instance_template_networks.yaml

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/68
- Added additionalProperties: false for nested objects
- Added support for "networkInterfaces[].accessConfigs[]", "disks",
"scheduling", "minCpuPlatform", "guestAccelerators",
"shieldedInstanceConfig", "sourceInstance", "sourceInstanceParams"

Fixes #68: DM/instance_template: refactoring

---

dm/templates/route/examples/route.yaml
dm/templates/route/route.py
dm/templates/route/route.py.schema
dm/templates/route/tests/integration/route.yaml

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/119
- Fixed arrays, objects and required fields (check for routeType + make
old scheme optional)
- Added missing fields: "description", "nextHopInstance",
"nextHopInstance", "nextHopNetwork", "nextHopGateway",
"nextHopVpnTunnel"

Fixes #119: DM/route: refactoring

---

infra/concourse/build/Dockerfile.lint

Fixes [terraform-google-module-template/issues/23](https://github.com/terraform-google-modules/terraform-google-module-template/issues/23)
- added [terraform_docs.sh](https://github.com/antonbabenko/pre-commit-terraform/blob/master/terraform_docs.sh)
- added `perl` as dependency for the script

Added terraform_docs.sh - workaround for HCL2 & terrafrom-docs

---

dm/templates/firewall/firewall.py
dm/templates/firewall/firewall.py.schema

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/99
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/91
- Upgraded compute-beta to compute-v1
- Added schema to "rules": "name", "description", "priority",
"sourceRanges", "destinationRanges", "sourceTags", "targetTags",
"sourceServiceAccounts", "targetServiceAccounts", "allowed", "denied",
"direction", "logConfig", "disabled"

Fixes #99: DM/firewall: refactoring

---

dm/templates/bigquery/bigquery_dataset.py
dm/templates/bigquery/bigquery_dataset.py.schema
dm/templates/bigquery/bigquery_table.py
dm/templates/bigquery/bigquery_table.py.schema
dm/templates/bigquery/tests/integration/bigquery.yaml

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/105
- Added missing fields to datasets: "friendlyName",
"defaultPartitionExpirationMs", "labels", "access"
- Added missing fields to tables: "description", "labels", "clustering",
"requirePartitionFilter", "externalDataConfiguration",
"encryptionConfiguration"
- Added uniqueItems: true and additionalProperties: false
- Fix template dependency
Notes:
- There is a race condition for dataset/table creation. [Relevant issue](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/127)

Fixes #105: DM/bigquery: refactoring

---

dm/templates/gke/examples/gke_regional.yaml
dm/templates/gke/examples/gke_regional_private.yaml
dm/templates/gke/examples/gke_zonal.yaml
dm/templates/gke/gke.py
dm/templates/gke/gke.py.schema
dm/templates/gke/tests/integration/gke.yaml

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/110
- Removed deprecated "nodeConfig", switch to "nodePools[].config"
- Removed deprecated "initialNodeCount", switch to
"nodePools[].initial_node_count"
- Removed deprecated "privateCluster", "masterIpv4CidrBlock" ->
"privateClusterConfig"
- Updated parameters: "masterAuth", "loggingService",
"monitoringService", "addonsConfig",
"ipAllocationPolicy" and others
- Added support for "nodePools[]", "binaryAuthorization", "autoscaling",
"networkConfig", "defaultMaxPodsConstraint",
"resourceUsageExportConfig", "authenticatorGroupsConfig",
"verticalPodAutoscaling", "tierSettings", …

Fixes #110: DM/gke: refactoring

---

dm/templates/pubsub/examples/pubsub.yaml
dm/templates/pubsub/examples/pubsub_push.yaml
dm/templates/pubsub/pubsub.py
dm/templates/pubsub/pubsub.py.schema
dm/templates/pubsub/tests/integration/pubsub.yaml

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/118
- Added topic fields: "labels"
- Added subscription fields: "pushConfig", "retainAckedMessages",
"messageRetentionDuration", "labels", "expirationPolicy"

Fixes #118: DM/pubsub: refactoring

---

dm/templates/ip_reservation/ip_address.py
dm/templates/ip_reservation/ip_address.py.schema
dm/templates/ip_reservation/ip_reservation.py.schema

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/132
- Addde version, links to docs
- Added missing fields: "prefixLength", "networkTier"
- Fixed field checks

Fixes #132: DM/ip_reservation: refactoring

---

dm/templates/healthcheck/healthcheck.py
dm/templates/healthcheck/healthcheck.py.schema

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/124
- Added support for missing fields: "description", "name"

Fixes #124: DM/healthcheck: refactoring

---

dm/templates/forwarding_rule/forwarding_rule.py
dm/templates/forwarding_rule/forwarding_rule.py.schema

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/141
- Fixed descriptions
- Added support for fields: "serviceLabel", "networkTier", "allPorts"

Fixes #141: DM/forwarding_rule: refactoring

---

dm/templates/dataproc/dataproc.py
dm/templates/dataproc/dataproc.py.schema

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/137
- Added missing fields: "labels", "<nodes>.imageUri",
"<nodes>.isPreemptible", "<nodes>.accelerators",
"softwareConfig.optionalComponents", "encryptionConfig"
- Mergeed master, nodes and secondary nodes

Fixes #137: DM/dataproc: refactoring

---

dm/templates/dns_managed_zone/README.md
dm/templates/dns_managed_zone/dns_managed_zone.py
dm/templates/dns_managed_zone/dns_managed_zone.py.schema
dm/templates/dns_managed_zone/examples/dns_managed_zone.yaml
dm/templates/dns_managed_zone/examples/dns_managed_zone_private.yaml
dm/templates/dns_managed_zone/examples/dns_managed_zone_private_visibility_config.yaml
dm/templates/dns_managed_zone/examples/dns_managed_zone_public.yaml
dm/templates/dns_managed_zone/tests/integration/dns_mz_cross_project.bats
dm/templates/dns_managed_zone/tests/integration/dns_mz_cross_project.yaml
dm/templates/dns_managed_zone/tests/integration/dns_mz_private.bats
dm/templates/dns_managed_zone/tests/integration/dns_mz_private.yaml
dm/templates/dns_managed_zone/tests/integration/dns_mz_prvt_vsblt_cfg.bats
dm/templates/dns_managed_zone/tests/integration/dns_mz_prvt_vsblt_cfg.yaml
dm/templates/dns_managed_zone/tests/integration/dns_mz_public.bats
dm/templates/dns_managed_zone/tests/integration/dns_mz_public.yaml
dm/templates/dns_managed_zone/tests/integration/dns_mz_simple.bats
dm/templates/dns_managed_zone/tests/integration/dns_mz_simple.yaml

#138 
- Switched to using gcp type provider
- Aligned resource names with the API documentation
- Added full schema validation against the API documentation (including all supported properties with their regular expressions for acceptable values)
- Added following integration test cases: 
- [Managed Zone with `public visibility`](tests/integration/dns_mz_public.bats)
- [Managed Zone with `private visibility`](tests/integration/dns_mz_private.bats)
- [Managed Zone with `private visibility config`](tests/integration/dns_mz_prvt_vsblt_cfg.bats)
- [Managed Zone with `cross-project reference`](tests/integration/dns_mz_cross_project.bats)
- Added version, updated inks to docs, examples and tests

DM/dns_managed_zone: refactoring #138

---

dm/templates/iam_member/iam_member.py

Project ID was forcefully overwritten to context.env['project']

[DM] Patch IAM member to projectID

---

dm/templates/dns_managed_zone/README.md
dm/templates/dns_managed_zone/dns_managed_zone.py.schema
dm/templates/dns_managed_zone/examples/dns_managed_zone_legacy.yaml
dm/templates/dns_managed_zone/tests/integration/dns_mz_bkwrd_cmptb.bats
dm/templates/dns_managed_zone/tests/integration/dns_mz_bkwrd_cmptb.yaml
dm/templates/dns_managed_zone/tests/integration/dns_mz_cross_project.bats
dm/templates/dns_managed_zone/tests/integration/dns_mz_cross_project.yaml
dm/templates/dns_managed_zone/tests/integration/dns_mz_private.bats
dm/templates/dns_managed_zone/tests/integration/dns_mz_private.yaml
dm/templates/dns_managed_zone/tests/integration/dns_mz_prvt_vsblt_cfg.yaml
dm/templates/dns_managed_zone/tests/integration/dns_mz_public.bats
dm/templates/dns_managed_zone/tests/integration/dns_mz_public.yaml
dm/templates/dns_managed_zone/tests/integration/dns_mz_simple.bats
dm/templates/dns_managed_zone/tests/integration/dns_mz_simple.yaml

#138 (updated scope)
- Added Backward Compatibility with the old property `zoneName`.
- Added legacy example template with the use of `zoneName` property.
- Added Integration Test for Backward Compatibility.
- Fixed not proper integration tests indentation inherited from previous tests.
- Added project parameter for `gcloud` calls. 
- Adjusted schema patterns with full match patterns where applicable.
- Added description for all the integration tests.

#138 - refactoring scope updated with backward compatibility and tests

---

infra/concourse/pipelines/terraform-google-kubernetes-engine.yml

This PR enables tests in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/207

Adding upstream nameservers tests to ci

---

dm/Makefile
dm/docs/userguide.md

Change Makefile target from `cft-prerequisites` to `prerequisites`.

Fix prerequisites Makefile target to align with docs and help

---

infra/concourse/pipelines/terraform-google-project-factory.yml

This commit updates the version of the integration test docker image to
version 2.0.0 which includes Terraform 0.12. This is needed to enable CI
testing for the impending Terraform 0.12 upgrade. NOTE: This change will
be a blocker for any open PRs that implement Terraform 0.11 syntax.

Update Project Factory integration test image

---

infra/concourse/pipelines/terraform-google-cloud-nat.yml

Use the `test/run_ci.sh` wrapper, as is standard in other CFT modules, and ensure that we're using an up-to-date `kitchen-terraform` Docker image.

Update terraform-google-cloud-nat CI workflow

---

infra/concourse/Makefile.BUILD
infra/concourse/build/Dockerfile.kitchen-terraform

Per conversation with @aaron-lane, this will go towards simplifying the `terraform-google-kubernetes-engine` Concourse pipeline by eliminating a presently-problematic intermediary build stage.
When this is approved, I plan to release it via `make build-image-kitchen-terraform && make release-image-kitchen-terraform`. `DOCKER_TAG_VERSION_KITCHEN_TERRAFORM` has been set to `2.0.1` in this PR.

Add kubectl to kitchen-terraform image

---

infra/concourse/pipelines/terraform-google-kubernetes-engine.yml

See https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/217 for additional context.
Marking this PR as **draft** until https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/217 is merged.

Remove intermediary kitchen-terraform image build steps from terraform-google-kubernetes-engine CI pipeline

---

infra/concourse/Makefile.BUILD
infra/concourse/build/Dockerfile.lint
infra/concourse/pipelines/terraform-google-project-factory.yml

This patch builds a new lint image with Terraform 0.12.3 which includes
the gsuite provider to fix the following error with the 2.3.0 image.
This patch also builds version 2.1.0 for both the terraform and
kitchen-terraform images, based on TF 0.12.3.
helpers/terraform_validate ./examples/project-hierarchy
Initializing modules...
- project-factory in ../../modules/gsuite_enabled
- project-factory.gsuite_group in ../../modules/gsuite_group
- project-factory.project-factory in ../../modules/core_project_factory
- project-prod-gke in ../../modules/gsuite_enabled
- project-prod-gke.gsuite_group in ../../modules/gsuite_group
- project-prod-gke.project-factory in ../../modules/core_project_factory
Initializing provider plugins...
- Checking for available provider plugins...
Provider "gsuite" not …

Update docker images for TF 0.12.3

---

infra/concourse/pipelines/terraform-google-network.yml

This commit updates both the lint and integration test docker images for
the network module to versions that will support the Terraform 0.12
upgrade.

Update docker images for network module

---

dm/templates/interconnect_attachment/interconnect_attachment.py
dm/templates/interconnect_attachment/interconnect_attachment.py.schema

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/183
- Added missing fileds: "pairingKey", "vlanTag8021q", "adminEnabled",
"candidateSubnets", "bandwidth", "partnerMetadata", "partnerAsn"

Fixes #183: DM/interconnect_attachment: refactoring

---

dm/templates/runtime_config/examples/runtime_config.yaml
dm/templates/runtime_config/runtime_config.py
dm/templates/runtime_config/runtime_config.py.schema
dm/templates/runtime_config/tests/integration/runtime_config.yaml
dm/templates/runtime_config/variable.py
dm/templates/runtime_config/variable.py.schema
dm/templates/runtime_config/waiter.py
dm/templates/runtime_config/waiter.py.schema

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/184
- Standardized naming

Fixes #184: DM/runtime_config: refactoring

---

dm/templates/dns_managed_zone/dns_managed_zone.py
dm/templates/dns_managed_zone/dns_managed_zone.py.schema
dm/templates/dns_managed_zone/tests/integration/dns_mz_cross_project.bats

#138 
- Fixed Backward Compatibility Support.
- Fixed pydocstyle D210, D202.
- Updated project property description
- Restricted dnsName pattern to comply with RFC. 1035
- Made Cros-Project test to exit if Cros-Project variable is not set

Fixed Backward Compatibility Support. Fixed pydocstyle D210, D202. #138

---

dm/templates/stackdriver_metric_descriptor/examples/stackdriver_metric_descriptor.yaml
dm/templates/stackdriver_metric_descriptor/stackdriver_metric_descriptor.py
dm/templates/stackdriver_metric_descriptor/stackdriver_metric_descriptor.py.schema
dm/templates/stackdriver_metric_descriptor/tests/integration/stackdriver_metric_descriptor.yaml

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/185
- Added support for "launchStage", deprecated "metadata.launchStage"
- Added checks for "unit"

Fixes #185: DM/stackdriver_metric_descriptor: refactoring

---

dm/templates/cloudbuild/cloudbuild.py
dm/templates/cloudbuild/cloudbuild.py.schema
dm/templates/cloudbuild/trigger.py
dm/templates/cloudbuild/trigger.py.schema

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/180
- Added checks to objects and arrays
- Fixed "artifacts.objects" property, add "options.workerPool, env,
secretEnv, volumes" for cloudbuild
- Added "tags", "github", "triggerTemplate.revision->commitSha" for
trigger

Fixes #180: DM/cloudbuild: refactoring

---

dm/templates/gke/gke.py

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/177
Do not get "clientCertificate" and "clientKey" when "latest" is used in the initialClusterVersion.

Enable GKE DM template to support 'latest' initial cluster version.

---

dm/templates/firewall/firewall.py
dm/templates/firewall/firewall.py.schema

Remove the deprecated "network" tag.
Add a "networkURL" to enable users to specify network URL. See issue "https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/233"

Add networkURL tag to firewall DM template.

---

dm/templates/org_policy/org_policy.py
dm/templates/org_policy/org_policy.py.schema
dm/templates/org_policy/tests/integration/org_policy.bats

Fixes #146 
- Fixed pydocstyle warnings
- Added schema validation against the API documentation
- Added project parameter to gcloud deployment-manager calls

Fixes #146

---

cli/go.mod
cli/go.sum

Update module dependancy for github.com/forseti-security/config-validator to make this buildable.
The original version was missing validator.Constraint

update module dependancy to make this buildable

---

dm/templates/cloud_router/cloud_router.py
dm/templates/cloud_router/cloud_router.py.schema

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/233
Enable cloud_router to accept network URL.
- add a new tag "networkURL" that accepts the URL of a network.

Enable cloud_router DM template to support networkURL.

---

README.md

So that users can see the contents of the directory without having to navigate one step up.

Linking to root directory instead of readme

---

infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh

Fixes #277 
- Added `replace_doc_generator`
Helper function to facilitate switch to a 0.12 compatible doc generator:
- replaces `terraform_docs`s markers with `pre-commit-terraform`s
markers for `terraform_docs.sh` - a wrapper around `terraform_docs`
- removes `combine_docfiles.py` script
- adds a copy of `terraform_docs.sh` script
- adds `terraform_validate` script

Helper function to facilitate switch to a 0.12 doc generator

---

dm/templates/vpn/vpn.py
dm/templates/vpn/vpn.py.schema

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/226
In this PR, we add static routing to VPN template
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/233
We also add routeURL and netURL to the schema so that users can specify the references of other resources in the config file.

Enable VPN DM template to support static routing.

---

infra/terraform/test-org/org/folders.tf
infra/terraform/test-org/org/locals.tf

Add `ci-folders` folder which is going to be a part of new testing approach with CloudBuild for [terraform-google-folders](https://github.com/terraform-google-modules/terraform-google-folders) module.

Add ci folder for `folders` module

---

cli/cmd/common.go
cli/deployment/config.go
cli/deployment/config_test.go

Before even looking inside yaml file for project ID, CLI was failing on cmd.setDefaultProjectID()
invocation when not provided ways to set project ID from:
--project argument,
default project env variable,
gcloud default project.
Behaviour after fix: as long default project ID is not mandatory, cft will not fail if project ID will could be found in YAML file.
Fail assert code added to config.GetProject() method.
Small typo fix "formated" -> "formatted" added.
Fixes #332

DM/CLI Error pick up the project ID from the YAML file

---

dm/CI/cft_base_container/Dockerfile
dm/CI/cft_base_container/cloudbuild.yaml
dm/CI/cft_base_contianer/cft_base_container
dm/Makefile
dm/docs/template_dev_guide.md

Additional scope implemented.
Fixed dm/CI/cft_base_container - wasn't able to build it initially.
Added make command to build cft-base-image to build it.
Added cft-test-bats command to run test locally, example command:
cd ./dm
make cft-test-bats TEST=templates/instance/tests/integration/instance.bats
Fixes #291

[DM local testing] Docker image and tutorial for local testing 

---

cli/Makefile
cli/deployment/api_client.go
cli/deployment/api_client_test.go
cli/deployment/config.go

DM/CLI Cross deployment reference was not even trying to look up the output of the other deployments.
Fixes #334

DM/CLI Not fail on cross-deployment references to existing deployments

---

infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh

Exclude *.svg files from lint checks

---

dm/templates/bigquery/examples/bigquery.yaml

The dependsOn property prevents the case that the table is created before the dataset exists.

added the dependsOn to the example

---

infra/build/developer-tools/build/scripts/task_helper_functions.sh

Let `gcloud` handle passing the service account creds to `gsutil`
This is a reasonable thing to do since we already perform the permanent `gcloud` authentication with the service account credentials in order to use `bq` here:
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/infra/build/developer-tools/build/scripts/task_helper_functions.sh#L344
So this PR reverts the `pass_credentials_to_gsutil` back to its default `true` value and removes the extra `.boto` file creation.

[devtools] Fix gsutil

---

infra/build/developer-tools/build/scripts/task_wrapper_scripts/terraform_docs.sh

- fix https://github.com/terraform-google-modules/terraform-google-lb-http/issues/66
Update terraform_docs_awk hack with a newer version from here:
https://github.com/cloudposse/build-harness/pull/174
Note that the PR I took it from wasn't reviewed yet (thus not merged into master branch yet), but seems to be fixing our issue in `terraform-google-lb-http` just fine. Also ran it on `generate_docs` of the `iam` module and the `kubernetes-engine` module -- and the readme docs generated were the same, so should be safe to merge.

Improve terraform_docs_awk hack which patches terraform-docs on tf 0.12

---

dm/templates/gcs_bucket/gcs_bucket.py
dm/templates/gcs_bucket/gcs_bucket.py.schema
dm/templates/gcs_bucket/tests/integration/gcs_35_iam_bindings.bats
dm/templates/gcs_bucket/tests/integration/gcs_35_iam_bindings.yaml

* Changed action to the new virtual type
* Added explicit dependencies to the GCS bindings
* Added bats-test for 35 GCS bindings

Changed GCS bucket 'setIamPolicy' action to virtual type

---

infra/build/developer-tools/build/scripts/task_helper_functions.sh

See https://github.com/terraform-google-modules/terraform-google-gcloud/pull/5

Ignore the cache directory when finding files for syntax checking

---

dm/templates/cloud_function/README.md

"Private by default" has actually been delayed until Jan 15. I also removed the conflicting note.

Remove outdated warning and correct the launch date 

---

infra/terraform/test-org/org/gsuite.tf
infra/terraform/test-org/org/outputs.tf

Used for project-factory tests of gsuite functionality.
Can later be used in other gsuite-related tests in other modules.
Note for @aaron-lane:
Added an output `ci_gsuite_sa_email` with the SA email which will need to be used when going through the delegation guide here:
https://developers.google.com/admin-sdk/directory/v1/guides/delegation
The guide has to be followed all the way up to granting SA the domain-wide access to Admin SDK Directory API.
Also we'll use the `project-factory-test-admin@test.infra.cft.tips` user account to impersonate this newly created SA account (https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/build/int.cloudbuild.yaml#L24).
Don't really know if any additional linkage has to be setup between …

[test-org] Create long-living SA which has G-Suite access.

---

infra/terraform/test-org/org/gsuite.tf
infra/terraform/test-org/org/outputs.tf

Create a new bucket to store and later retrieve the gsuite key.
Also has an example on how to retrieve the key as the comment.
```hcl
data "google_storage_object_signed_url" "ci_gsuite_sa_json" {
bucket   = "ci-gsuite-sa-secrets"
path     = "gsuite-sa.json"
duration = "1m"
}
data "http" "ci_gsuite_sa_json" {
url = data.google_storage_object_signed_url.ci_gsuite_sa_json.signed_url
}
output "gsuite_sa_json" {
value     = data.http.ci_gsuite_sa_json.body
sensitive = true
}
```

[test-org] Create a secrets bucket to store gsuite sa key in.

---

dm/templates/firewall/firewall.py.schema

This change is required to allow creation of rules with target service accounts

Add targetServiceAccounts to firewall.py.schema

---

dm/templates/network/network.py.schema

Fixes https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/506
Removed oneOf from network.py.schema.

Fixes #506: Network template incorrectly handles empty networks

---

cli/go.mod
cli/scorecard/cmd.go
cli/scorecard/inventory.go
cli/scorecard/violations.go

Update to allow CFT Scorecard to read IAM and Resources inventories from Stdin when bucket and dir-path where not passed.

Allow CFT Scorecard to read JSON metadata from Stdin

---

dm/CHANGELOG.md
dm/templates/gke/gke.py
dm/templates/gke/gke.py.schema

This PR adds support for the `releaseChannel` setting when creating a GKE cluster.
Documentation: https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.ReleaseChannel

Adding support for releaseChannel setting

---

cli/scorecard/cmd.go
cli/scorecard/score.go
cli/scorecard/violations.go

- bugfix for input flag validation to check for either one of the 3 CAI input methods
- add flag.parse() to get rid of "ERROR: logging before flag.parse" output to stderr as result of new config-validator version introduced in recently updated go.mod
- increase NewScanner buffer size to handle lines in CAI export that is larger than 64k, usually from BigQuery Tables

Varies scorecard bugfixes

---

cli/docs/scorecard.md
cli/scorecard/cmd.go
cli/scorecard/score.go

New scorecard feature to include violation metadata fields of string type in txt or csv output. 
Use cases include a user-defined priority for each constraint, resource parent/project number/project id, or any additional information that is not covered in resource name and violation message.
The expectation is that these metadata fields need to be defined in constraint templates.

scorecard - new feature to include additional metadata fields in output

---

cli/go.sum
cli/scorecard/score.go
cli/scorecard/violations.go

- remove duplicate violations
- fix constraint name in txt output
fixes some issues in https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/584

Scorecard - fixes for compatiblity with new config validator

---

dm/templates/network/network.py.schema

During fixing issue #559 this template was incorrectly changed braking existing templates. This PR reverts the change.

Revert changes from #559 and import the subnetwork.py template

---

dm/templates/instance/instance.py.schema

The `enum` values were incorrect for initializeParams.
See docs here: https://cloud.google.com/compute/docs/reference/rest/v1/instances#Instance.FIELDS.inlinedField_29

Remove enum from initializeParams diskType

---

infra/build/developer-tools/build/install_bats.sh

`make build-image-developer-tools` fails due to `1-2.0.0` invalid version
Removing hard coded string `-1` in install_bats.sh

Removing hard coded string `-1` in install_bats.sh

---

.github/workflows/build-push-cft-devtools.yml

Build CFT dev tools image only when pushed to `master`

Restrict building new dev tools images only when pushed to master

---

config-connector/solutions/iam/README.md
config-connector/solutions/iam/kpt/README.md
config-connector/solutions/iam/kpt/member-iam/0-namespace.yaml
config-connector/solutions/iam/kpt/member-iam/Kptfile
config-connector/solutions/iam/kpt/member-iam/README.md
config-connector/solutions/iam/kpt/member-iam/iampolicymember.yaml
config-connector/solutions/iam/kpt/member-iam/iamserviceaccount.yaml

Adding a new solution for Config Connector. This solution comes from the TF CFT member_iam [example](https://github.com/terraform-google-modules/terraform-google-iam/tree/master/examples/member_iam)/[submodule](https://github.com/terraform-google-modules/terraform-google-iam/tree/master/modules/member_iam).

Add Config Connector solution member-iam

---

config-connector/solutions/projects/kpt/simple-project/Kptfile
config-connector/solutions/projects/kpt/simple-project/README.md
config-connector/solutions/projects/kpt/simple-project/project.yaml
config-connector/tests/README.md
config-connector/tests/ccs-test/cmd/root.go
config-connector/tests/ccs-test/go.mod
config-connector/tests/ccs-test/util/util.go
config-connector/tests/testcases/projects/kpt/simple-project/original_values.yaml
config-connector/tests/testcases/projects/kpt/simple-project/required_fields_only.yaml

* Updated the original solution to make project-id a required setter.
* Added the feature to append a random ID when the value needs to be globally unique.

[KCC] Add the testcase for simple-project solution

---

infra/terraform/test-org/ci-comment-build-trigger-function/function_source/main.py

- Fix nor condition bug 
@morgante there is another _bug_ where if the [`_DOCKER_TAG_VERSION_DEVELOPER_TOOLS` in a lint.cloubuild.yaml ](https://github.com/terraform-google-modules/terraform-google-cloud-storage/blob/805a6d897443f99bae3c6e877ccb586837a64c86/build/lint.cloudbuild.yaml#L24)is less that `0.11.0` then the comment will fail as the comment helper is not in any image below `0.11.0`.  
We can fix this using `distutils.version` but I was thinking of keeping as is. My thoughts are, this way we can make sure all modules that use this feature are at a min version `0.11.0`. WDYT?

Fix condition bug in comment bot

---

config-connector/solutions/projects/helm/owned-project/templates/project.yaml
config-connector/solutions/projects/helm/simple-project/templates/project.yaml

The numerical IDs need to be quoted from within Helm to work robustly.

Quote orgID and folderID using helm

---

infra/terraform/test-org/ci-triggers/locals.tf

- We should exclude by the name of the folder created, which has ` ci-` prepended.

Fix example-foundation name exclusion

---

infra/terraform/test-org/org/policy.tf

Fixes https://github.com/terraform-google-modules/terraform-google-project-factory/pull/428#pullrequestreview-451005075
Adds `google_access_context_manager_access_policy` for test-org. Currently there is one that exists created manually which can be imported or deleted and recreated.
```
POLICY_ID=$(gcloud access-context-manager policies list --organization="${ORG_ID}" --format="value(name)")
gcloud access-context-manager policies delete "${POLICY_ID}" 
```

Add default access_context_manager_access_policy to test org

---

infra/terraform/test-org/ci-comment-build-trigger-function/function_source/main.py

Fix issue where bot was not ignoring `autogen` dir
Example: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/602#issuecomment-664090306
Cause:
- as we are cloning a repo manually within the buildstep we need to cd into the REPO_DIR for each stage
- this was resulting in [`find_files` unable to match the `autogen` folder ](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/d427b256faca6721f20418fae3ac8a4555d2faa4/infra/build/developer-tools/build/scripts/task_helper_functions.sh#L62)to ignore fmt

fix: CFT bot ignore autogen fmt

---

infra/build/developer-tools/build/install_shellcheck.sh

Builds are breaking due to https://github.com/koalaman/shellcheck/issues/1871 and hence updating as recommended.

Update install_shellcheck in devtools image

---

dm/templates/cloudbuild/examples/cloudbuild_trigger.yaml
dm/templates/cloudbuild/trigger.py.schema

Fixes #602 
Revert `triggerTemplate` schema to match
https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/RepoSource
Fix example to match
https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.trigger

Fix Cloud Build trigger example & template schema

---

dm/templates/cloud_sql/cloud_sql.py.schema

Currently, Google Cloud SQL APIs allow the new versions of database engines and remove the oldest one:
- MySQL: add v8.0, remove v5.5
- PostgreSQL: add v10 and v12
- SQLServer: remove ENTERPRISE 2016
Changed schema to embrace this change.

Updated cloud_sql.py.schema to allow new versions

---

.github/workflows/release-cli.yml
.github/workflows/update-tooling.yml

`set-env` commands are now deprecated due to a security vulnerability and will be fully disabled soon. This PR migrates them to the new approach.
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

fix: Update set-env commands for tooling and release GitHub workflows

---

.github/workflows/build-push-cft-devtools.yml
.github/workflows/release-cli.yml

`GoogleCloudPlatform/github-actions/setup-gcloud` is now deprecated and replaced by[`google-github-actions/setup-gcloud`](https://github.com/google-github-actions/setup-gcloud) for new features/fixes.

chore: update setup-gcloud actions repo

---

cli/scorecard/score.go

The current behavior is that multiple violations are outputted as individual JSON objects instead of as an array. This produces invalid JSON output that can't be directly read by other programs.
This PR fixes that by outputting an array of violations.

Scorecard: Fix JSON output for multiple violations

---

infra/terraform/test-org/ci-comment-build-trigger-function/function_source/main.py
infra/terraform/test-org/ci-comment-build-trigger-function/versions.tf

fixes https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/795
tested locally https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/788
Comment bot was not catching `check_generate_modules` as `check_generate_modules` required `/workspace/autogen_modules.json` but bot was operating in `/workspace/${MODULE_NAME}/autogen_modules.json`. This fix will now clone into current workspace.

fix: check_generate_modules for comment bot

---

infra/terraform/test-org/ci-comment-build-trigger-function/function_source/main.py

Example foundations lint test requires a specific pre-step (https://github.com/terraform-google-modules/terraform-example-foundation/pull/298/commits/85dec2517f5990a8487f7b59c072934784a0dff5) to work around nested providers in 0.13. 
This will be added as a step in the cloud build lint pipeline (https://github.com/terraform-google-modules/terraform-example-foundation/pull/323) but not incorporated into the bot as it not useful for general modules.

fix: disable comment bot on example foundation

---

infra/terraform/test-org/org/bigquery_external_data.tf
infra/terraform/test-org/org/external_data/bar.csv
infra/terraform/test-org/org/external_data/bigquery-external-table-test.csv
infra/terraform/test-org/org/external_data/foo.csv
infra/terraform/test-org/org/locals.tf
infra/terraform/test-org/org/outputs.tf

This PR adds publicly accessible static files to be used in CI testing for the (terraform-google-bigquery)[https://github.com/terraform-google-modules/terraform-google-bigquery] module. The PR: https://github.com/terraform-google-modules/terraform-google-bigquery/pull/105 introduces a feature that allows provisioning external tables, and we want to ensure that we have proper integration testing in place for this feature. 
This PR creates a new project, bucket, bucket IAM member, and 3 bucket objects (all CSV files) that will be used in integration testing. 
I was pointed to this spot in this repository by @morgante who has reviewed my work. 
To develop this, I switched out the backend locally and applied the configuration to my own personal GCP project, and verified that the integration …

Add external data for testing with Terraform BigQuery module

---

.github/workflows/build-push-cft-devtools.yml

[Looks like](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/runs/2116609256?check_suite_focus=true#step:4:1449) for pulling `gcr.io/cloud-marketplace/google/ubuntu1804:latest`, we need to be authed. This moves the auth to build step.

fix: move helper config to build step

---

.github/workflows/build-push-cft-devtools.yml

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/886 was not triggered as no changes were made to `"infra/build/**"`. This adds the action config to triggers.

fix: add action yaml to trigger

---

cli/go.mod
cli/scorecard/proto_test.go

In #902, I suggested eventually moving to protojson.
According to https://github.com/golang/protobuf/issues/1121#issuecomment-627554847, that library does not support a stable serialization output. That means that the test in proto_test.go would become flaky.
The suggestion there is "Instead of syntactically comparing the serialized form of a message, the test should semantically compare the structured form of a message", so I've done that here by loading the got and want strings as JSON and comparing the structured JSON.

Test stringViaJSON structure, not exact string

---

infra/build/developer-tools-light/Dockerfile
infra/build/developer-tools/Dockerfile

bumps TF installer to newer image with new GPG key
https://discuss.hashicorp.com/t/terraform-updates-for-hcsec-2021-12/23570
https://github.com/sethvargo/hashicorp-installer/commit/8ce045027fcdeebd82e9b0a33026f717f3fadf8c

fix: bump TF installer 

---

infra/terraform/test-org/ci-triggers/triggers.tf

fixes https://github.com/terraform-google-modules/terraform-example-foundation/issues/468
Tested in example-foundation fork with 1 trigger:
https://github.com/bharathkkb/terraform-example-foundation/pull/3 skipped as only md changes
https://github.com/bharathkkb/terraform-example-foundation/pull/4 ran as expected

fix: skip int tests if only doc changes

---

infra/build/developer-tools-krm/Dockerfile

`-u` could result in dep updates for golangci-lint potentially breaking the build

fix: skip update pkgs for golangci-lint

---

infra/build/developer-tools/Dockerfile
infra/build/developer-tools/build/scripts/task_helper_functions.sh

fixes #934 
Tested lint check with [GKE module](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine)
Overall in time in serial ~50% improvement, parallel ~40% improvement.
Disk space savings of ~11GB
benchmarks:
with cache, in serial, 8m33.596s, ~ 700 MB on disk
no cache, in serial, 17m50.396s,  ~ 12 GB on disk
with cache, in parallel,  2m14.301s, ~ 700 MB on disk
without cache, in parallel,  6m11.804s, ~ 12 GB on disk

fix: remove tf-bundler, add caching

---

infra/terraform/test-org/org/locals.tf

This pull request adds **`cloud-run`** to **`gcp_org_modules`** to generate the test build.
@bharathkkb

Added cloud-run to gcp_org_modules trigger

---

infra/blueprint-test/examples/krm_blueprints_with_test/test/integration/vpc-example-custom/vpc_custom_test.go
infra/blueprint-test/pkg/krmt/krm.go

Exposes option for passing in additional setters to upsert. This is useful for global resources that require a random unique name.

fix(krm-test): add option for custom setters

---

infra/blueprint-test/pkg/tft/terraform.go
infra/blueprint-test/pkg/tft/terraform_test.go

This adds support for setting complex type outputs from setup as inputs. 
TF requires list/map env vars to be [formatted as an HCL expression](https://www.terraform.io/docs/cli/commands/plan.html#input-variables-on-the-command-line) but Terratest does not directly expose its [conversion function](https://github.com/nlowe/terratest/blob/2ba8cabb767dd7ab1a918138540501fee8d6dd56/modules/terraform/format.go#L66).  As  a workaround, we extract the formatted HCL expression from the var arg slice. We cannot switch from the env var approach to var args directly due to https://github.com/hashicorp/terraform/issues/28764

feat: support complex type setup outputs

---

infra/terraform/test-org/tf-validator/iam.tf

In order to run tests during magic modules ci we need to add it's service account to the permissions list here.

Add magic_modules service account to project perm list

---

infra/blueprint-test/pkg/discovery/discover.go
infra/blueprint-test/pkg/discovery/discover_test.go

`GetConfigDirFromTestDir` is used by the framework to compute config dir based on the test dir name. Currently it does not take into account test dir path as example/fixtures are well known. However for use in CLI, I would like to compute config dir from relative to a test dir path.

fix(bptest): compute config discovery from int test dir

---

.github/workflows/release-cli.yml

fixes https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/1009 release
This adds the workflow file to triggers for CLI build release. Since publish steps are gated by `if: env.LAST_VERSION != env.CURRENT_VERSION`, this should be no op when re run after a release.

chore: trigger CLI release job on workflow file changes

---

.github/workflows/release-cli.yml

fixes https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/1031
In #1028, I restricted the permissions granted to GITHUB_TOKEN in workflows. After some debugging it seems like write [permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) are needed on `contents` to create a release.

fix: CLI release

---

.github/workflows/release-cli.yml

Recent [release](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/runs/4887033451?check_suite_focus=true) failed due to old default go version in the runner. This sets up correct version similar to [test workflow](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/0573029a7c8d7aaad072e2feccfef7645579ce64/.github/workflows/test-cli.yml#L35)

chore: use correct version of go for CLI release

---

cli/bptest/cmd.go

fix(cli): skip printing help text for test failures

---

infra/blueprint-test/pkg/discovery/discover.go
infra/blueprint-test/pkg/gcloud/gcloud.go
infra/blueprint-test/pkg/tft/terraform.go
infra/blueprint-test/pkg/utils/env.go
infra/blueprint-test/pkg/utils/files.go

Make setup sa key more flexible for other tests.
+ Minor improvements.

feat: (Blueprint) Allow customization of setup sa key

---

infra/blueprint-test/pkg/discovery/discover.go

This improves log message for discovery to not say "error" since its recoverable and may confuse users.

chore: better log message for recoverable error info

---

.github/workflows/build-push-cft-devtools.yml
.github/workflows/test-cft-devtools.yml
infra/build/Makefile

- workaround for https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/1095 by pinning gcloud to last known working version 375.0.0
- fixes https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/1096 by adding a job to test build in PR and adding a step for opening an issue for failed builds on main

fix: pin gcloud to 375.0.0 to fix devtools build

---

cli/bptest/cmd.go
cli/bptest/convert.go
cli/bptest/convert_test.go
cli/bptest/templates/blueprint_test.go.tmpl
cli/bptest/templates/discover_test.go.tmpl
cli/bptest/templates/go.mod.tmpl
cli/bptest/testdata/cb/newAll.yaml
cli/bptest/testdata/cb/newTarget.yaml
cli/bptest/testdata/cb/oldAll.yaml
cli/bptest/testdata/cb/oldTarget.yaml
cli/bptest/testdata/kitchen-tests/simple-example/controls/gcloud.rb
cli/bptest/testdata/kitchen-tests/simple-example/inspec.yml
cli/go.mod
cli/go.sum

This adds a new `convert` command that
- removes kitchen tests and replaces them with a skeleton blueprint test with inputs
- updates cloud build file to use cft cli commands

feat: add experimental convert command for cli test

---

.github/workflows/update-tooling.yml

fix: exclude `porch/` when checking kpt release versions
Fixes #1116

fix: exclude `porch/` when checking kpt releases

---

infra/build/Makefile

fixes https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/1095
Removed pinned gcloud version as upstream issue is fixed

fix: revert pinned gcloud version

---

infra/terraform/test-org/ci-triggers/locals.tf

- Removed folders/ prefix from folder id var - needs to just be id
- Removed duplicate folders/ prefix in ancestry variable
Basically, org.outputs.folders["key"] is in the format "folders/12345"

Fixed variable definitions

---

infra/terraform/test-org/ci-triggers/locals.tf

tf validator "ancestry path" expects non-plural type names for historical reasons

Made ancestry match legacy format

---

.github/release-please.yml
.release-please-manifest.json
release-please-config.json

Fixes #1141 
Example PR: https://github.com/apeabody/cloud-foundation-toolkit/pull/2
NOTE: Remove "release-as" from release-please-config.json after the first release (v0.0.1).  "bootstrap-sha" can optionally be removed after the first release.

chore: create release-please.yml

---

release-please-config.json

@bharathkkb - The tag delimiter is now correct, but go needs the tag and nested path to match, e.g. `infra/blueprint-test/v0.0.1`.  Hopefully setting `"component": "infra/blueprint-test"` will suffice, otherwise we might need to set the package name to `"infra/blueprint-test"`.

fix: update infra/blueprint-test release-please

---

infra/terraform/test-org/org-iam-policy/iam.tf

Looks like this SA was deleted and was causing IAM cleaner builds to fail. Not sure what this was used for, I can't find the project either.

fix: remove deleted SA from test org

---

infra/terraform/test-org/org/locals.tf

Since module-template is in terraform-google-modules org.

chore: update module-template org

---

cli/bpmetadata/cmd.go
cli/bpmetadata/main.go
cli/cmd/blueprint.go

This adds a top level `blueprint` command to  the `cft` cli and adds the following commands as sub-commands to it:
- `test`
- `builds`
- `metadata` - new and in-progress
`cft test` will continue to work until we change that to `cft blueprint test` and take `test` out of the root command.

feat:adds base commands for blueprint metadata

---

infra/blueprint-test/pkg/utils/logger.go
infra/blueprint-test/pkg/utils/logger_test.go

This adds a new logger that can log to disk instead of stdout. This helps keep cloudbuild logs tidier with additional details in disk and uploaded using [CB artifacts](https://cloud.google.com/build/docs/building/store-artifacts-in-cloud-storage#store-artifact-storage).

feat: blueprint-test file logger

---

infra/build/developer-tools/build/scripts/task_helper_functions.sh

example: https://github.com/GoogleCloudPlatform/terraform-google-media-cdn-vod/blob/main/smpte.mp4

fix: exempt mp4 files from whitespace and newline

---

infra/terraform/test-org/github/renovate.json

This will greatly reduce the number of PRs by consolidating both the Google and Google-Beta, and also their major and minor versions (eliminate minor v3 PR, and keep the separate v4 PR).  It should also attempt to "widen" the constraint rather than upgrading v3 > v4.

feat: consolidate TPG and TPG-Beta, major and minor into single PR

---

infra/blueprint-test/examples/simple_pet_module/main.tf
infra/blueprint-test/pkg/tft/terraform.go
infra/blueprint-test/test/terraform_redeploy_test.go

This adds a new `RedeployTest` strategy for ensuring TF blueprints can be deployed n times in a single project.
Each deployment is done in a separate workspace with a deferred cleanup until all the redeployments have been verified.

feat: new test strategy for redeploy validation

---

.github/workflows/release-cli.yml

Aligning this to what we use to devtools build push.

chore: use a newer gcloud version for CLI release

---

.github/conventional-commit-lint.yaml

With this config, the bot will always use PR title
fixes #1304

chore: create conventional commit bot config

---

.github/workflows/update-tooling.yml

It looked like the gcrane updater failed to get version. Releases is an array so I switched to getting the latest release.

chore: gcrane update fix

---

.github/workflows/update-tooling.yml
infra/blueprint-test/go.mod
infra/blueprint-test/pkg/kpt/kpt.go
infra/blueprint-test/pkg/kpt/status.go
infra/blueprint-test/pkg/krmt/krm.go
infra/blueprint-test/pkg/utils/bincheck.go
infra/blueprint-test/pkg/utils/version.go
infra/build/Makefile

NOTE: `kpt live apply` no longer includes "unchanged" status, so this somewhat changes the behavior of `DefaultVerify` to verify all are applied successfully.  If the verification of "unchanged" status is used by other consumers (@kaariger) of this package we should revisit the design.
Tested with `go test -v krm_simple_blueprint_test.go`
Fixes: #1190

fix: update blueprint-test for kpt v1.0.0-beta.16+

---

cli/Makefile
cli/bpmetadata/cmd.go

fix: bpmetadata cli accepts abs and relative paths

---

infra/blueprint-test/pkg/kpt/kpt.go
infra/blueprint-test/pkg/kpt/setters.go
infra/blueprint-test/pkg/kpt/status.go
infra/blueprint-test/pkg/krmt/krm.go
infra/blueprint-test/pkg/tft/terraform.go
infra/blueprint-test/pkg/utils/env.go
infra/blueprint-test/pkg/utils/files.go
infra/blueprint-test/pkg/utils/version.go

* Fixes #1445 
* Adds `kpt.GetKptVersion()`
* Adds `utils.GetWD()`
* Go code formating
Tested with `go test -v krm_simple_blueprint_test.g`

fix: kpt tests without existing working dir

---

cli/go.mod

Somehow this got reverted with #1440. Adding it back in.

fix: removes the replace directive for gatekeeper

---

.github/workflows/update-tooling.yml

Didn't realize this earlier but we inadvertently introduced a bug as part of 9f87d3c that stopped updating devtools.

fix: updates the update-tooling-workflow for cft and k8s

---

infra/terraform/test-org/org-iam-policy/cloudbuild.yaml

Current constraint requires `>= 1.4.4`

chore: bump reset IAM to use TF 1.4.x

---

infra/terraform/test-org/ci-triggers/locals.tf
infra/terraform/test-org/org/locals.tf

Onboarding https://github.com/GoogleCloudPlatform/terraform-ml-image-annotation-gcf. This repo hosts UP3.1.

chore: add terraform-ml-image-annotation-gcf repo

---

infra/terraform/test-org/org/locals.tf

Enabled enable periodics for another repo for testing (cc @tpryan ). Will add reporter GHA workflow out of band for now until we do some testing.

chore: enable periodics on three-tier

---

.github/workflows/release-cli.yml

Overlooked as part of https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/1593

chore: update release-cli to GO 1.18

---

cli/Makefile
cli/bpmetadata/validate.go
cli/util/file.go
cli/util/file_test.go

Previously the validation logic would specifically look for metadata files in the current (or provided) path and in the modules/ dir underneath it. Now it walks the path provided regardless of the folder structure and finds/validates metadata files everywhere.

feat: updates metadata validation to walk a path

---

infra/terraform/modules/repositories/main.tf

Appears to worked in this test: https://github.com/terraform-google-modules/terraform-google-vm/pull/313
Somewhat unclear as dpebot has pull

chore: change ci_team to triage

---

infra/blueprint-test/pkg/utils/asserthttp.go
infra/blueprint-test/pkg/utils/asserthttp_test.go

Fixes b/290946766.
Add utilities for end-to-end testing of web services associated with a blueprint.
This will simplify https://github.com/GoogleCloudPlatform/terraform-dynamic-python-webapp/blob/main/infra/test/integration/testhelper.go and help other JSS apps such as https://github.com/GoogleCloudPlatform/terraform-dynamic-javascript-webapp to implement tests without reimplementation or code copying.
Let's see what it will look like to revise existing code based on this PR:
https://github.com/GoogleCloudPlatform/terraform-dynamic-python-webapp/blob/2bc215906d953735b46625a389d71ec2f5251ae4/infra/test/integration/testhelper.go#L51C3-L51C86
```go
r, err := http.NewRequest(http.MethodGet, firebase_url, nil)
if err != nil {
t.Fatal(err)
}
utils.NewAssertHTTP().AssertSuccessWithRetry(t, r, …
```

feat: Add HTTP Assert test helpers

---

infra/build/developer-tools/build/scripts/task_helper_functions.sh

See https://github.com/HSA-Integration/Annotate-images-with-Vertex-AI/pull/92, which uses pb and index files.

fix: Update task_helper_functions.sh to omit pb and index files

---

infra/blueprint-test/pkg/utils/asserthttp.go
infra/blueprint-test/pkg/utils/asserthttp_test.go

Fixes #1726
This is a broader change than originally intended, as expanded test coverage surfaced new bugs and that process repeated a couple times.
1. Retries are now configurable using the new `WithHTTPRequestRetries`
2. API know longer uses t.Fatal, instead it uses t.Error for better alignment with testify assert semantics.
3. Logging now uses `GetLoggerFromT` for more consistent output with other library functions
4. If response body is part of the assert, they will be checked even if the status code doesn't match.
5. Logic is simplified via wrapped errors
6. `httpRetryCondition` now returned two booleans: first indicates response success, second that retry is called for.
7. Test coverage is significantly expanded and uses a table testing approach to improve readability and facilitate …

refactor: fix AssertHTTP retry and improved CFT practices

---

.github/workflows/update-tooling.yml

* `base` is needed for the on-release trigger as it's from a commit

chore: update update-tooling

---

infra/blueprint-test/pkg/bq/bq.go

If the local environment does not have a .bigqueryrc file, using the tool will faill as bq initializing itself does not output valid json data.

fix: add bq init step to create local config file

---

infra/terraform/test-org/ci-triggers/triggers.tf

This PR updates the Terraform Example Foundation CI-trigger ignore filter to ignore png files

chore: update CI-trigger ignore filter to ignore png files

---

infra/terraform/test-org/github/resources/renovate.json

combine GO and Dev-Tools update PRs while setting GO version to 1.21

chore: update renovate.json

---

infra/terraform/test-org/github/resources/stale.yml

- `dependencies` is for prs, not issues
- We should also exempt pending releases

chore: correct stale pr exemptions

---

infra/blueprint-test/examples/simple_krm_blueprint/pod.yaml
infra/blueprint-test/go.mod
infra/blueprint-test/go.sum
infra/blueprint-test/pkg/tft/terraform.go
infra/blueprint-test/test/krm_simple_blueprint_test.go
infra/blueprint-test/test/setup/main.tf

Prevent concurrent writes, or reads during writes, to the tft plugin cache.

feat(tft): add filemutex for tft plugin cache

---

infra/terraform/test-org/ci-triggers/secrets.tf

To be used in testing setting up Cloud Build repository connections to GitHub/GitLab repositories for a new Infrastructure Manager blueprint.

feat: Add secrets for GitHub/GitLab tokens

---

infra/terraform/test-org/org-iam-policy/iam.tf

Looks like tag admin is explicitly needed to create tags. https://github.com/terraform-google-modules/terraform-google-project-factory/pull/885 was failing in prepare and I tried adding tag admin out of band which then passed prepare.

fix: allow CI robots to create tags

---

infra/terraform/test-org/org/locals.tf

* I am adding `local.jss_common_group` ([jump-start-solutions-admins GitHub team](https://github.com/orgs/GoogleCloudPlatform/teams/jump-start-solutions-admins)) to the `dataanalytics-eventdriven` JSS.
* Members of this GitHub team (including myself and Karl) may sometimes help unblock small PRs (like Renovate PRs) and regularly work on continuous improvement projects — across all JSS repos.
* I'll also work on improving the related instructions (from the JSS authoring guide) via [cl/622203416](http://cl/622203416).
* CC: @fellipeamedeiros (just for visibility)

fix: Add local.jss_common_group to dataanalytics-eventdriven JSS

---

.github/workflows/lint.yaml

Testdata may contain invalid config for test purposes

chore: Exclude tflint plugin from lint workflow

---

infra/blueprint-test/README.md

* Correct syntax for markdown links
* Update syntax for aside/quote/note

docs: syntax fixes for blueprint-test/README.md

---

cli/Makefile
cli/bptest/cmd.go
cli/bptest/convert.go
cli/bptest/stages.go
cli/bptest/stages_test.go

We added plan support in https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/2258 but I missed to add it to CLI

feat: expose plan stage via test cli

---

infra/terraform/test-org/ci-triggers/triggers.tf

Doesn't appear the Integration tests cover foundation-deployer, so I've opened PR https://github.com/terraform-google-modules/terraform-example-foundation/pull/1218 for a dedicated workflow.

chore(CI): ignore example.tfvars and helpers/foundation-deployer in example-foundation-int tests

---

infra/blueprint-test/pkg/tft/terraform.go

Adds a general purpose BPT(tft) output which returns all output as a `gjson.Result`

feat(tft): add GetJsonOutput()

---

infra/terraform/test-org/github/resources/renovate.json

- All renovate to update repo's to GO 1.22 as dev-tools 1.21

chore(CI): bump repo's renovate go version

---

infra/terraform/test-org/org/locals.tf

Correcting the owners to megelatim(https://github.com/megelatim), which the correct github user name.

chore: Update locals.tf for megelatim

---

infra/terraform/test-org/org/github.tf
infra/terraform/test-org/org/locals.tf

* See Google-internal bug: [b/351840017](http://b/351840017)
* We would like to stop all deployments of JSS 15.1.
* JSS 15.1 = Deploy a Java application with Compute Engine
* CC: @donmccasland, @duncantech

fix: Disable JSS 15.1 periodic tests

---

infra/terraform/test-org/org/locals.tf

This PR add new blueprint for apphub to blueprint list.

chore: Add terraform-google-apphub to list of repos

---

infra/build/developer-tools/build/scripts/task_helper_functions.sh

There is a subsequent `cd`, so we should use a non-referential path.

chore(CI): fix custom tflint path

---

cli/bpmetadata/cmd.go
cli/bpmetadata/tfconfig.go
cli/bpmetadata/tfconfig_test.go
cli/testdata/bpmetadata/metadata/existing_interfaces_with_one_connection_metadata.yaml
cli/testdata/bpmetadata/metadata/existing_interfaces_with_some_connections_metadata.yaml
cli/testdata/bpmetadata/metadata/existing_interfaces_without_connections_metadata.yaml
cli/testdata/bpmetadata/metadata/new_interfaces_no_connections_metadata.yaml

Preserve manually added connections fields in the metadata.yaml files when the metadata files are recompiled for whatever the reason (version updates, dependency changes, etc).
Also added test cases to make sure the logic works in multiple conditions.

feat: preserve manually added connections fields

---

cli/bpmetadata/cmd.go

In blueprint metadata generation step, versions.tf needs to be loaded for generating version metadata. 
Currently versions.tf file is being only searched in the root directory of the blueprint. This fails to generated version metadata for the submodules.
This feature was added in https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/2496

fix: Version config path should look for versions.tf in current blueprint dirctory

---

cli/bpmetadata/schema/gcp-blueprint-metadata.json
cli/bpmetadata/schema/generate.go
cli/bpmetadata/validate_test.go
cli/testdata/bpmetadata/schema/valid-display-metadata-alternate-defaults.yaml

This is a follow-up PR of https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/2453. The AlternateDefault value field is of type `google.protobuf.Value`. Similar to other fields of same type, it requires workaround so that JsonSchema doesn't treat it as object.

feat: Support display metadata AlternateDefault validate

---

cli/bptest/lint_interface.go
cli/bptest/lint_interface_test.go

Add `BLUEPRINT_LINT_DISABLE` env var to bypass `cft test lint` rules when set to 1.

feat: Bypass `cft test lint` rules

---

.github/workflows/build-push-cft-devtools.yml
infra/build/Makefile

also add issue write permissions for `open issue if push failed`

fix(dev-tools): make, not bash

---

infra/blueprint-test/pkg/golden/golden.go
infra/blueprint-test/pkg/golden/golden_test.go

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/2719 wasn't compatible with invalid JSON from testing empty paths.  This adds backwards compatibility to the original implementation, while still resolving the whitespace equality issue.

fix: JSONEq() whitespace backwards compatible

---

infra/terraform/test-org/org/locals.tf

Add Pub/Sub devs with terraform experience to the pubsub terraform module owners.

chore: add pubsub devs as pubsub module owners

---

infra/terraform/test-org/org/locals.tf

This PR also enables metadata validation for terraform-google-dataflow

chore: Enable metadata validation in lint test for terraform-google-bigtable

---

infra/terraform/test-org/org/locals.tf

This should include the new list of maintainers. If there is a way to add a group that would be preferred.

chore: Update Cloud Run maintainers
