dm/src/cloud_foundation_toolkit/deployment.py
References:
- https://github.com/GoogleCloudPlatform/deploymentmanager-samples/blob/master/google/resource-snippets/cloudkms-v1/kms.yaml
- https://github.com/GoogleCloudPlatform/deploymentmanager-samples/issues/127
- https://github.com/GoogleCloudPlatform/deploymentmanager-samples/issues/169
=> Add configVersion to DM_CONFIG_KEYS

infra/terraform/applications/concourse.tf
This configuration has been successfully applied.
=> Enable local auth in Concourse

dm/templates/gke/gke.py
https://github.com/GoogleCloudPlatform/deploymentmanager-samples/issues/446
=> Fixes #446 GKE template output error (nodeIpv4CidrSize)

dm/templates/project/project.py, dm/templates/project/project.py.schema
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/57
- Added "labels" support
- Added resource name prefix
- Updated compute-beta to compute-v1
- Fixed deprecated gcp-types/compute-v1:compute.subnetworks.setIamPolicy
bindings
- Refactored default resources removal: remove code duplication
- Added usageExportBucket name prefix
=> Fixes #57: DM/project: refactoring

dm/templates/autoscaler/autoscaler.py, dm/templates/autoscaler/autoscaler.py.schema
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/67
- Added additionalProperties: false for nested object
=> Fixes #67: DM/autoscaler: refactoring

dm/templates/managed_instance_group/examples/managed_instance_group.yaml, dm/templates/managed_instance_group/examples/managed_instance_group_healthcheck.yaml, dm/templates/managed_instance_group/managed_instance_group.py, dm/templates/managed_instance_group/managed_instance_group.py.schema, dm/templates/managed_instance_group/tests/integration/managed_instance_group.bats, dm/templates/managed_instance_group/tests/integration/managed_instance_group.yaml
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/69
- Added additionalProperties: false for nested objects
=> Fixes #69: DM/managed_instance_group: refactoring

dm/templates/instance/instance.py.schema
=> Update diskImage doc to mention valid image

dm/templates/route/route.py, dm/templates/route/tests/integration/route.bats
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/119
Small typo, rechecked tests
=> Fixes #119: DM/route: refactoring

dm/templates/iam_member/iam_member.py.schema
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/116
Added version, links to docs
=> Fixes #116: DM/iam_member: refactoring

dm/templates/bastion/bastion.py, dm/templates/bastion/bastion.py.schema, dm/templates/bastion/tests/integration/bastion.bats, dm/templates/instance/instance.py
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/101
- Fixed instance.py outputs (it lacks internalIp/externalIP)
- Fixed endless loops in tests
=> Fixes #101: DM/bastion: refactoring

dm/templates/backend_service/backend_service.py, dm/templates/backend_service/backend_service.py.schema, dm/templates/backend_service/examples/backend_service_global.yaml, dm/templates/backend_service/examples/backend_service_regional.yaml, dm/templates/backend_service/tests/integration/backend_service.yaml
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/103
- Added new fields: "backends[].maxRatePerEndpoint,
.maxConnectionsPerEndpoint", "iap", "customRequestHeaders[]"
- Changed healthCheck to healthChecks[]
- Added checks for INTERNAL/EXTERNAL LB schemes for all relevant fields
- Added checks for backends[].balancingMode
=> Fixes #103: DM/backend_service: refactoring

dm/templates/kms/kms.py, dm/templates/kms/kms.py.schema
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/117
- Added missing algorithms
=> Fixes #117: DM/kms: refactoring

dm/templates/iam_custom_role/organization_custom_role.py, dm/templates/iam_custom_role/organization_custom_role.py.schema, dm/templates/iam_custom_role/project_custom_role.py, dm/templates/iam_custom_role/project_custom_role.py.schema
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/115
- Added support for "stage" field
=> Fixes #115: DM/iam_custom_role: refactoring

dm/templates/iam_member/examples/iam_member.yaml, dm/templates/iam_member/iam_member.py, dm/templates/iam_member/iam_member.py.schema
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/162
Added support for folders and organizations:
gcp-types/cloudresourcemanager-v1:virtual.projects.iamMemberBinding
gcp-types/cloudresourcemanager-v2:virtual.folders.iamMemberBinding
gcp-types/cloudresourcemanager-v1:virtual.organizations.iamMemberBinding
=> Fixes #162: [DM] IAM_member folder and org support

dm/templates/nat_gateway/nat_gateway.py, dm/templates/nat_gateway/nat_gateway.py.schema, dm/templates/nat_gateway/tests/integration/nat_gateway.bats, dm/templates/route/route.py, dm/templates/route/tests/integration/route.bats
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/123
=> Fixes #123: DM/nat_gateway: refactoring

dm/templates/ssl_certificate/ssl_certificate.py, dm/templates/ssl_certificate/ssl_certificate.py.schema, dm/templates/ssl_certificate/tests/integration/ssl_certificate.yaml
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/148
=> Fixes #148: DM/ssl_certificate: refactoring

dm/templates/url_map/url_map.py, dm/templates/url_map/url_map.py.schema
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/153
=> Fixes #153: DM/url_map: refactoring

dm/templates/target_proxy/target_proxy.py, dm/templates/target_proxy/target_proxy.py.schema, dm/templates/target_proxy/tests/integration/target_proxy.yaml
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/154
- Upgraded compute api version
- Fixed fields descriptions, add checks to arrays and objects
- Added support for "sslCertificates"
=> Fixes #154: DM/target_proxy: refactoring

dm/templates/external_load_balancer/examples/external_load_balancer_http.yaml, dm/templates/external_load_balancer/examples/external_load_balancer_https.yaml, dm/templates/external_load_balancer/examples/external_load_balancer_ssl.yaml, dm/templates/external_load_balancer/examples/external_load_balancer_tcp.yaml, dm/templates/external_load_balancer/external_load_balancer.py, dm/templates/external_load_balancer/external_load_balancer.py.schema, dm/templates/external_load_balancer/tests/integration/external_load_balancer.bats, dm/templates/external_load_balancer/tests/integration/external_load_balancer.yaml
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/140
=> Fixes #140: DM/external_load_balancer: refactoring

dm/templates/internal_load_balancer/internal_load_balancer.py, dm/templates/internal_load_balancer/internal_load_balancer.py.schema
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/143
=> Fixes #143: DM/internal_load_balancer: refactoring

dm/templates/haproxy/haproxy.py, dm/templates/haproxy/haproxy.py.schema
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/142
- Fixed imports
=> Fixes #142: DM/haproxy: refactoring

dm/templates/gke/examples/gke_regional.yaml, dm/templates/gke/examples/gke_regional_private.yaml, dm/templates/gke/gke.py, dm/templates/gke/gke.py.schema
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/171
=> Fixes #171: DM: Bug in GKE template examples

infra/concourse/pipelines/terraform-google-kubernetes-engine.yml
This PR enables tests in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/203
=> Adding workload-metadata-config-local test

cli/README.md, cli/cmd/root.go
=> Fix couple of typographical errors

dm/templates/iam_member/iam_member.py, dm/templates/iam_member/iam_member.py.schema, dm/templates/project/project.py
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/175
=> Fixes #175: IAM needs to depends on SA existance

dm/templates/interconnect/interconnect.py, dm/templates/interconnect/interconnect.py.schema
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/182
- Updateed/added fields: "linkType", "requestedLinkCount",
"interconnectType"
=> Fixes #182: DM/interconnect: refactoring

dm/templates/dns_records/dns_records.py, dm/templates/dns_records/dns_records.py.schema, dm/templates/dns_records/tests/integration/dns_records.bats
#139 
- Aligned resource names with the API documentation
- Added schema validation against the API documentation, RFC 1035 compliant regular expressions for dnsName
- Added version, updated links to docs
- Fixed pydocstyle warnings
- Added project parameter for tests setup/teardown
=> Refactored dns_records template #139

dm/templates/vpn/tests/integration/vpn.bats, dm/templates/vpn/tests/integration/vpn.yaml, dm/templates/vpn/vpn.py, dm/templates/vpn/vpn.py.schema
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/186
- Added missing router property
=> Fixes #186: DM/vpn: refactoring

dm/templates/cloud_tasks/queue.py, dm/templates/cloud_tasks/queue.py.schema, dm/templates/cloud_tasks/task.py, dm/templates/cloud_tasks/task.py.schema
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/179
- Added version
=> Fixes #179: DM/cloud_tasks: refactoring

dm/templates/network_peering/network_peering.py, dm/templates/network_peering/network_peering.py.schema, dm/templates/network_peering/tests/integration/network_peering.bats
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/145
- Added support for "networkPeering" field
=> Fixes #145: DM/network_peering: refactoring

dm/templates/logsink/logsink.py, dm/templates/logsink/logsink.py.schema
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/144
=> Fixes #144: DM/logsink: refactoring

infra/concourse/pipelines/terraform-google-cloud-nat.yml
Fixes https://github.com/terraform-google-modules/terraform-google-cloud-nat/issues/14
Related: https://github.com/terraform-google-modules/terraform-google-cloud-nat/pull/12, https://github.com/terraform-google-modules/terraform-google-cloud-nat/issues/11
=> Update terraform-google-cloud-nat images to Terraform 0.12.x

infra/concourse/pipelines/terraform-google-folders.yml, infra/terraform/test_fixtures/terraform-google-folders.tf
=> Add Concourse pipeline for Folders module

infra/concourse/pipelines/terraform-google-service-accounts.yml, infra/concourse/pipelines/terraform-google-sql-db.yml, infra/terraform/test_fixtures/terraform-google-service-accounts.tf, infra/terraform/test_fixtures/terraform-google-sql-db.tf
=> Add Concourse pipeline for SQL DB and Service Accounts modules

infra/concourse/pipelines/terraform-google-vpn.yml
=> Update VPN pipeline for Terraform 0.12

infra/concourse/pipelines/terraform-google-iam.yml, infra/terraform/test_fixtures/outputs.tf, infra/terraform/test_fixtures/terraform-google-cloud-nat.tf, infra/terraform/test_fixtures/terraform-google-iam.tf, infra/terraform/test_fixtures/terraform-google-jenkins.tf, infra/terraform/test_fixtures/terraform-google-vm.tf
This is a continuation of the work started in #209
=> Add Concourse pipeline for IAM module

dm/templates/forseti/client.py, dm/templates/forseti/client.py.schema, dm/templates/forseti/forseti.py, dm/templates/forseti/forseti.py.schema, dm/templates/forseti/server.py, dm/templates/forseti/server.py.schema
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/181
=> Fixes #181: DM/forseti: refactoring

infra/concourse/pipelines/terraform-google-event-function.yml
https://github.com/terraform-google-modules/terraform-google-event-function/issues/20
Updated CI pipeline for Event function
=> Add support for Terraform 0.12 to Event Function pipeline

infra/concourse/pipelines/terraform-google-vm.yml
Fixes tests for https://github.com/terraform-google-modules/terraform-google-vm/pull/16
=> Docker image versions updated for tests vm module with terraform-0.12 

infra/concourse/pipelines/terraform-google-kubernetes-engine.yml, infra/terraform/test_fixtures/terraform-google-kubernetes-engine.tf
https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/180
Updated GKE CI pipeline for beta module
=> Fixes #180: Add tests for beta submodules/examples

infra/concourse/pipelines/terraform-google-address.yml
Fixes tests for  https://github.com/terraform-google-modules/terraform-google-address/pull/10
=> Versions of containers fixed

infra/concourse/pipelines/terraform-google-forseti.yml, infra/terraform/test_fixtures/terraform-google-forseti.tf
This pull request is paired with https://github.com/forseti-security/terraform-google-forseti/pull/216
=> Use Project Factory and configure network in Forseti test fixture

infra/terraform/test_fixtures/terraform-google-forseti.tf
This branch contains additional patches to supplement #260.
=> Patch Forseti infrastructure

dm/templates/bigquery/bigquery_table.py, dm/templates/healthcheck/tests/integration/healthcheck.bats, dm/templates/instance/instance.py, dm/templates/instance/tests/integration/instance_1_nic.yaml, dm/templates/instance/tests/integration/instance_2_nics.yaml, dm/templates/instance_template/tests/integration/instance_template.yaml, dm/templates/instance_template/tests/integration/instance_template_networks.bats, dm/templates/instance_template/tests/integration/instance_template_networks.yaml, dm/templates/shared_vpc_subnet_iam/tests/integration/shared_vpc_subnet_iam.yaml
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/269
- Fixed templates/bigquery/tests/integration/bigquery.bats
=> [WIP] Fixes #269: DM dev branch quality control

infra/concourse/pipelines/terraform-google-jenkins.yml
Fixes tests for https://github.com/terraform-google-modules/terraform-google-jenkins/pull/12
=> Container's versions modified for terraform-google-jenkins

dm/templates/dns_managed_zone/examples/dns_managed_zone_private_visibility_config.yaml
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/273
Added fixme
=> Fixed #273: DNS Zone example - add FIXME

dm/templates/pubsub/tests/integration/pubsub.bats, dm/templates/pubsub/tests/integration/pubsub.yaml
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/135
Added and fixed tests
=> Fixed #135: DM/Add subscription expiration policy to Pub/Sub template

dm/templates/cloud_sql/examples/cloud_sql_private_network.yaml
Changed settings.ipConfiguration.privateNetwork value example to FIXME style
Fixes #296
=> CloudSQL Private IP example

dm/templates/backend_service/examples/backend_service_global.yaml
Fixes #272
Added required properties:
- loadBalancingScheme
- sessionAffinity
- portName
- maxUtilization (switched to UTILIZATION balancingMode)
=> Fixed backend_service/examples/backend_service_global.yaml

cli/deployment/api_client.go
Removed default fail message log from command.runGClound() function, moved appropriate logging messages to functions invoking command.runGCloud().
As long command.GetStatus() method used before deployment creationg to check if deployment with same name already exists, gcloud exectuion fail message removed from it.
Fixes #335
=> DM/CLI Hide or list gcloud execution error in case it's expected error

infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh
=> Added JPEG and PNG file extentions to exclude from `find_files` function

infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh
* Fix [Issue 21](https://github.com/terraform-google-modules/terraform-google-vpc-service-controls/issues/21)
=> Add SA activation to init_credentials function

cli/README.md, cli/report/cmd.go
minor fixes to 'report' readme; and hide bucket option under 'report' for now because it does not work yet
=> minor fixes to readme; and hide bucket option for now 

dm/templates/iam_member/iam_member.py.schema
Defining projectID was causing schema violation.
=> [DM] fixing IAM member binding schema

dm/CHANGELOG.md, dm/templates/project/README.md, dm/templates/project/project.py, dm/templates/project/project.py.schema
=> SharedVPC IAM support on the folder level

infra/terraform/test-org/ci-triggers/backend.tf, infra/terraform/test-org/ci-triggers/locals.tf, infra/terraform/test-org/ci-triggers/outputs.tf, infra/terraform/test-org/ci-triggers/triggers.tf, infra/terraform/test-org/ci-triggers/versions.tf, infra/terraform/test-org/org/locals.tf
=> Cloud Build triggers creation

dm/templates/project/project.py.schema
=> Add project labels check to the project.py.schema

dm/templates/network/subnetwork.py, dm/templates/network/subnetwork.py.schema
To allow setup of INTERNAL_HTTPS_LOADBALANCING reserved range subnet
=> Add subnetwork properties purpose & role

dm/CHANGELOG.md, dm/templates/project/project.py, dm/templates/project/project.py.schema
* Fixed #433
* Fixed GKE SA role binding dependency
* Updated schema
=> Enabled container API instead of compute

cli/cmd/common.go, cli/report/report.go, cli/scorecard/score.go, cli/scorecard/violations.go
I run static checkers, identified a couple findings on unused variables, and fixed them accordingly.
=> resolve static check findings

dm/CHANGELOG.md, dm/templates/resource_policy/README.md, dm/templates/resource_policy/examples/resource_policy.yaml, dm/templates/resource_policy/resource_policy.py, dm/templates/resource_policy/resource_policy.py.schema, dm/templates/resource_policy/tests/integration/resource_policy.bats, dm/templates/resource_policy/tests/integration/resource_policy.yaml
=> Add Resource Policy DM template

dm/templates/gcs_bucket/gcs_bucket.py, dm/templates/gcs_bucket/gcs_bucket.py.schema, dm/templates/gcs_bucket/tests/integration/gcs_iam_bucket_policy_only.bats, dm/templates/gcs_bucket/tests/integration/gcs_iam_bucket_policy_only.yaml
=> Added support of bucketPolicyOnly setting for gcs_bucket template

dm/CHANGELOG.md, dm/templates/logsink/README.md, dm/templates/logsink/examples/logsink_new_bq_destination_in_external_project.yaml, dm/templates/logsink/examples/logsink_new_bucket_destination_in_external_project.yaml, dm/templates/logsink/examples/logsink_new_pubsub_destination_in_external_project.yaml, dm/templates/logsink/logsink.py, dm/templates/logsink/logsink.py.schema, dm/templates/logsink/tests/integration/logsink_external_project.bats, dm/templates/logsink/tests/integration/logsink_external_project.yaml
=> Added log sink template with external bucket

dm/templates/external_load_balancer/external_load_balancer.py.schema
=> Add list of SSL certs to the target proxy in the external LB template

cli/launchpad/folder.go, cli/launchpad/folder_test.go, cli/launchpad/generic.go, cli/launchpad/org.go, cli/launchpad/runtime.go, cli/launchpad/runtime_test.go, cli/testdata/launchpad/folder/folder_1_nested.yaml, cli/testdata/launchpad/folder/org_2_nested_conflict.yaml
Added missing code for nested folders and detecting conflicts on folder definitions.
Fixes #535.
=> Launchpad nested folders and conflict definitions

cli/docs/scorecard.md, cli/scorecard/cmd.go, cli/scorecard/inventory.go
Feature to refresh Cloud Asset Inventory export files in GCS bucket
=> scorecard - Cloud Asset Inventory refresh feature

cli/scorecard/cmd.go, cli/scorecard/proto.go, cli/scorecard/score.go
Sorry for the PR spam, with this I think I'm happy with the output-metadata-fields feature now.
=> scorecard - enhancement to handle output metadata of all types

dm/templates/cloud_sql/cloud_sql.py
For example needed to create an instance and give to CloudSQL' serviceAccount the permission to write on a bucket
=> Added serviceAccountEmailAddress to output fields

dm/templates/cloud_sql/cloud_sql.py
With this change is possible to have two grants for the same user but with different source hosts
=> CloudSQL - Same user with different host

infra/terraform/test-org/ci-triggers/locals.tf, infra/terraform/test-org/ci-triggers/triggers.tf
1. Added the env variable for billing iam test account ID
2. Added the billing iam test account ID as a local variable
=> Added billing iam test account ID to Cloud Build config

infra/terraform/test-org/ci-triggers/triggers.tf
Updated test_billing_account_id ONLY for billing-iam module.
=> Updated test_billing_account only for billing-iam

infra/terraform/test-org/ci-triggers/triggers.tf
Changed module name from terraform-google-billing-iam to terraform-google-iam for trigger.
=> Update module name to google-iam for iam trigger

infra/terraform/test-org/ci-triggers/triggers.tf
Changed to each.key from local.repo_folder for applying billing_iam_test_account.
=> Fixed module variable error to each.key

dm/CHANGELOG.md, dm/templates/cloud_sql/cloud_sql.py, dm/templates/cloud_sql/cloud_sql.py.schema
Permit multiple CloudSQL in the same deployment with same database name or same users
=> DB and user name collision

dm/CHANGELOG.md, dm/templates/project/project.py, dm/templates/project/project.py.schema
=> Fixing bucket name issue

dm/templates/gke/gke.py.schema
A number of properties in the GKE template have incorrect types, this fixes the ones I've run across so far.
=> GKE schema fixes

CODEOWNERS
@maqiuyujoyce @AlexBulankou Please take a look and LMK if you want anyone else added as an approver.
=> Add roles for KCC team to CODEOWNERS

config-connector/solutions/projects/kpt/simple-project/Kptfile, config-connector/solutions/projects/kpt/simple-project/README.md, config-connector/solutions/projects/kpt/simple-project/project.yaml
This is a proposed implementation of a sample kpt package for creating a project in GCP using Config Connector CRDs
=> Simple project (KCC Solution)

infra/terraform/test-org/org/locals.tf
Configuration of Cloud Build for Composer repo
=> Added composer to modules

config-connector/solutions/iam/kpt/storage-bucket-iam/Kptfile, config-connector/solutions/iam/kpt/storage-bucket-iam/README.md, config-connector/solutions/iam/kpt/storage-bucket-iam/iampolicymember.yaml
made substitution for bucket name
re-arranged setters, wrote README
added instructions for setting bucket-name
=> Implemented storage-bucket-iam KCC Solution

.github/workflows/update-tooling.yml
Remove myself from reviewer list for action PRs
=> Remove myself from reviewer list for action PRs

config-connector/tests/README.md
As we discussed in #651, I'm uploading the test-cli to remove the dependency on Go.
=> [KCC] Remove the dependency on Go for test-cli users

config-connector/solutions/iam/helm/service-account/README.md
Found some minor issue in the README of service-account helm solution.
=> [KCC] Fix the README of service-account helm solution

cli/Makefile
@morgante Can the updated cli with new scorecard features be released? 
Thanks!
=> CLI - Increment version number

.github/workflows/build-push-cft-devtools.yml, .github/workflows/release-cli.yml, cli/Makefile, cli/cmd/version.go
This should help us to release faster with less toil.
=> Add GitHub action for releasing CLI.

cli/Makefile, cli/docs/scorecard.md, cli/scorecard/cmd.go, cli/scorecard/proto.go, cli/testdata/scorecard/policy-library/policies/templates/gcp_org_policy_skip_default_network.yaml
- Updated the approach to convert org policy data from json to proto and some explanation on why it needs to be handled that way
- Minor update to user guide to add Windows executable 
- Minor update to scorecard help menu to sync with latest features
=> Scorecard - Org policy fix

config-connector/solutions/iam/helm/storage-bucket-iam/Chart.yaml, config-connector/solutions/iam/helm/storage-bucket-iam/README.md, config-connector/solutions/iam/helm/storage-bucket-iam/templates/iampolicymember.yaml, config-connector/solutions/iam/helm/storage-bucket-iam/values.yaml
Config Connector compatible yaml to enable permissions for a storage bucket.
=> [KCC] Adding Helm support for Storage Bucket IAM

CODEOWNERS
=> Add @bharathkkb to CODEOWNERS

dm/templates/gke/gke.py.schema
- Updated schema to respect the updated WorkloadIdentity settings (https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#Cluster.WorkloadIdentityConfig)
=> [DM] updated GKE templates

infra/terraform/test-org/ci-comment-build-trigger-function/function_source/main.py, infra/terraform/test-org/ci-comment-build-trigger-function/function_source/requirements.txt
Fixes issue where builds may take +10m
- Adds build timeout for bot
=> fix: Add build timeout for bot

infra/terraform/test-org/ci-triggers/locals.tf, infra/terraform/test-org/org/locals.tf, infra/utils/requirements.txt
And add folder for Anthos Platform
=> Addd requirements for cleanup script & new folder

infra/build/developer-tools/build/install_dependencies.sh
=> fix: add python3 headers for dev tools image

infra/terraform/test-org/org/gsuite.tf
It is needed to run tests in terraform-google-group module
=> Add missing API to gsuite testing project

dm/templates/bigquery/bigquery_table.py, dm/templates/bigquery/bigquery_table.py.schema
Fixes #877.
My first PR, please let me know of anything.
=> add hive partitioning support on bigquery_table dm template #877

infra/build/developer-tools/build/data/Gemfile, infra/build/developer-tools/build/data/Gemfile.lock
=> Upgrade kitchen-terraform to 5.7.2

infra/terraform/test-org/org-iam-policy/cloudbuild.yaml
=> fix: bump IAM cleaner runner image to TF 0.14

infra/build/developer-tools/build/scripts/task_helper_functions.sh
=> fix: fmt lint with cache dir

infra/terraform/test-org/org/locals.tf
Repo: https://github.com/GoogleCloudPlatform/terraform-google-network-forensics
=> chore: add network forensics module

infra/terraform/test-org/org/prow.tf
These will be used as env vars in test containers
=> fix: add krm test constants

infra/build/Makefile, infra/build/developer-tools-krm/build/scripts/prow_entrypoint.sh, infra/build/developer-tools-krm/build/scripts/runner.sh
This adds some helpers in KRM image for DIND setup and cleanup. DIND is required for running kpt fns in tests.
=> feat: prow dind helpers

infra/blueprint-test/pkg/tft/terraform.go
fixes  #1002 
This exports GetTFOptions from tft package
=> feat: export GetTFOptions method for tft

infra/terraform/test-org/tf-validator/iam.tf
Correcting a mistake in my last PR where I used added incorrect cloudbuild SA
=> correct cloud build service account for magic modules ci

.github/workflows/test-cli.yml
fixes https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/1024
=> chore: add CLI CI

.github/workflows/build-push-cft-devtools.yml, .github/workflows/release-cli.yml, cli/Makefile
follow up from https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/1008
=> chore: update GHA workflows for WIF

infra/terraform/test-org/ci-triggers/triggers.tf
Hey folks, 
This pull request fixes #1032
=> fix: Adds ignoring .md in sub-dirs for integration build

cli/bptest/cmd.go, cli/bptest/list.go, cli/bptest/run.go, cli/bptest/run_test.go, cli/bptest/stages.go, cli/bptest/stages_test.go, cli/cmd/root.go, cli/go.sum
This adds run functionality for running a test using the CLI
=> feat: test cli run cmd

cli/Makefile
cutting a new release with newly added test commands
=> chore: release CFT CLI version v0.4.2

.github/workflows/update-tooling.yml
Adds a workflow_dispatch trigger to allow running this workflow via the GH UI
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
=> chore: allow running workflow through UI

infra/blueprint-test/pkg/gcloud/gcloud.go, infra/blueprint-test/pkg/gcloud/gcloud_test.go, infra/blueprint-test/pkg/tft/terraform.go, infra/blueprint-test/pkg/utils/files.go, infra/blueprint-test/test/setup/simple_tf_module/main.tf, infra/blueprint-test/test/setup/simple_tf_module/outputs.tf
fixes https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/999
=> feat(tft): activate creds from setup

infra/blueprint-test/pkg/krmt/krm.go, infra/blueprint-test/pkg/tft/terraform.go
fixes https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/998
=> fix: mark tests as skipped due to test config

infra/blueprint-test/pkg/golden/golden.go, infra/blueprint-test/pkg/golden/golden_test.go
This adds sanitization functionality which allows modification of goldenfile data. A few common sanitizers are included in the package for helping us scrub values that change between test runs.
=> feat: add goldenfile sanitizers

infra/blueprint-test/go.mod, infra/blueprint-test/go.sum, infra/blueprint-test/pkg/kpt/kpt.go, infra/blueprint-test/pkg/kpt/setters.go
part of #1087 
/cc @g-awmalik @juliankatz
=> feat: remove list-setter dep for kpt

infra/terraform/test-org/ci-comment-build-trigger-function/function_source/main.py
cloud-foundation-training has some custom logic pre build to create valid TF
=> chore: skip comment bot on cloud-foundation-training repo

cli/bptest/list.go, cli/bptest/list_test.go
fixes https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/1082
=> feat: bpt skip hidden dirs during discovery

infra/blueprint-test/pkg/golden/golden.go
Based on suggestion in https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/1158#discussion_r816001407 as this is a common pattern
=> feat: add golden string sanitizer option

infra/blueprint-test/go.mod, infra/blueprint-test/go.sum, infra/blueprint-test/pkg/utils/transforms.go
This adds a helper for deleting a json value specified by path. This could be useful when used with goldenfiles where we want to assert most values are equal except for one or two values which are non deterministic.
=> feat: add transform func for removing a json value by path

infra/terraform/test-org/org-iam-policy/iam.tf, infra/terraform/test-org/test-cleanup/.terraform.lock.hcl, infra/terraform/test-org/test-cleanup/cleanup.tf
bump to use https://github.com/terraform-google-modules/terraform-google-scheduled-function/pull/77 and reconcile IAM used for IAM cleanup which was removing some project cleaner roles.
cc @daniel-cit
=> chore: bump cleaner, reconcile iam

release-please-config.json
fixes semver for https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/1168
=> chore: remove release as version

release-please-config.json
* Use "blueprint" test in the pull request title rather than component="infra/blueprint-test" as the `/` appears to cause issues with the release process.
* Remove the bootstrap-sha as no longer needed after first release.
=> chore: update blueprint-test release-please

infra/terraform/test-org/ci-triggers/triggers.tf
=> Made tfv tests get run for release branches as well as the main branch

infra/terraform/test-org/ci-triggers/triggers.tf
Discussed removing this with @ludoo as have migrated to GHA for tests.
=> chore: Remove tf pytest helper triggers

infra/terraform/test-org/org/locals.tf
* already updated org/CI-triggers/github
=> chore: add data-fusion to terraform config

infra/blueprint-test/pkg/tft/terraform.go, infra/blueprint-test/test/terraform_simple_bpt_test.go
=> feat: expose setup outputs via tft

infra/terraform/test-org/ci-triggers/.terraform.lock.hcl, infra/terraform/test-org/ci-triggers/backend.tf, infra/terraform/test-org/ci-triggers/locals.tf, infra/terraform/test-org/ci-triggers/triggers.tf
Setup for https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/1176
=> feat: expose SFB test deployment for other blueprints

infra/build/developer-tools/build/install_cloud_sdk.sh
=> install terraform-tools

infra/build/developer-tools/build/install_dependencies.sh
* Fixes: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/1208
* Add cookiecutter for [terraform-google-module-template](https://github.com/terraform-google-modules/terraform-google-module-template/blob/master/test/test.sh)
=> fix: update jinja2 and add cookiecutter for deps

infra/terraform/test-org/org-iam-policy/iam.tf
fixes https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/1186
=> Add reset of billing account iam policy

infra/terraform/test-org/org/locals.tf
These are for the Solutions in Console Project
=> feat: adding two blueprints

infra/blueprint-test/pkg/gcloud/gcloud.go, infra/blueprint-test/pkg/tft/terraform.go, infra/blueprint-test/test/tfvet_test.go
=> add project ID param to gcloud beta terraform vet

cli/Makefile
CLI with
- https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/1228 
- https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/1224
=> chore: release CLI v0.4.5

infra/terraform/test-org/org/locals.tf
This is for the Solutions in Console Project.
=> feat: adding one blueprint

infra/terraform/test-org/ci-triggers/locals.tf, infra/terraform/test-org/ci-triggers/logs.tf, infra/terraform/test-org/ci-triggers/triggers.tf
Setup infra to leverage filelogger added in https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/1234
Currently allowlisted to one repo where I plan to experiment and solidify the UX before we add to other repos.
=> feat: setup infra for filelogger

README.md
=> chore: add link to cft and fabric comparison

infra/build/developer-tools-light/Dockerfile, infra/build/developer-tools/Dockerfile, infra/build/developer-tools/build/install_terraform.sh
=> feat: inline TF installation method

infra/terraform/modules/branch_protection/main.tf, infra/terraform/modules/branch_protection/variables.tf, infra/terraform/modules/repo_file/main.tf, infra/terraform/modules/repo_file/variables.tf, infra/terraform/test-org/github/.terraform.lock.hcl, infra/terraform/test-org/github/main.tf, infra/terraform/test-org/github/outputs.tf, infra/terraform/test-org/github/protection.tf, infra/terraform/test-org/github/renovate.json, infra/terraform/test-org/org/locals.tf
* Add branch protection support for gcp repos
* Automatically set branch protection using the repo's default branch
* Add renovate.json to repos
=> chore: support gcp repos and add renovate.json

.github/workflows/update-tooling.yml
@bharathkkb quick check to prevent #1282
=> chore: validate tool version isn't missing

infra/terraform/test-org/github/.terraform.lock.hcl, infra/terraform/test-org/org/.terraform.lock.hcl, infra/terraform/test-org/org/locals.tf, infra/terraform/test-org/org/policy.tf
Update GH topics. Also sets an explicit quota project so access policy does not complain.
=> chore: update topics

infra/terraform/test-org/org/locals.tf
Add @ericyz to k8s owners and update labels, onboard workflows https://github.com/GoogleCloudPlatform/terraform-google-cloud-workflows/issues/1
=> chore: add eric to codeowner, update labels, onboard workflows

infra/build/Makefile, infra/build/developer-tools/Dockerfile, infra/build/developer-tools/build/install_tinkey.sh
Install [Tinkey ](https://github.com/google/tink/blob/master/docs/TINKEY.md) in developer-tools image
=> chore: install tinkey in developer-tools image

infra/terraform/modules/repo_file/main.tf
* TF state has been updated to match change
=> chore: fix variable name

infra/terraform/test-org/org/locals.tf
Added cloud functions module to the repo list
=> feat: added cloud functions to the repo list

infra/terraform/test-org/org/locals.tf
Removed an owner from cloud armor module.
=> chore: removed owner from cloud armor module

infra/terraform/test-org/github/resources/trusted-contribution.yml
Add `renovate-bot` for forking-renovate vs existing `renovate[bot]`
=> feat: add 'renovate-bot' for forking-renovate

cli/Makefile, cli/go.mod
=> fix: removing replace directive for gatekeeper

infra/terraform/test-org/ci-triggers/locals.tf, infra/terraform/test-org/org/locals.tf
* This is still in **draft** mode. Please do not review yet.
* I will be asking questions around this during the office hours (with @g-awmalik).
* This is analogous to https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/1424 — but for the Blueprint at [github.com/GoogleCloudPlatform/terraform-ecommerce-microservices-on-gke](https://github.com/GoogleCloudPlatform/terraform-ecommerce-microservices-on-gke).
=> chore: onboard ecommerce microservices app repo

cli/Makefile, cli/util/git.go, cli/util/git_test.go
=> fix: removes repo name validation

infra/terraform/test-org/org/locals.tf
=> fix: change codeowners for run and functions

infra/terraform/test-org/org-iam-policy/iam.tf
see https://github.com/GoogleCloudPlatform/terraform-google-itar-architectures/blob/main/test/setup/iam.tf
=> fix: add org-level roles for ITAR CI

cli/Makefile, cli/bpmetadata/cmd.go, cli/bpmetadata/display_test.go, cli/bpmetadata/proto/bpmetadata_ui.proto, cli/bpmetadata/repo.go, cli/bpmetadata/repo_test.go, cli/bpmetadata/schema/bpmetadataschema.json, cli/bpmetadata/types.go, cli/bpmetadata/types_ui.go
=> fix: updates annotation tag for author field

infra/terraform/test-org/org-iam-policy/iam.tf
=> fix: dev user access

cli/bpmetadata/cmd.go, cli/bpmetadata/schema/bpmetadataschema.json, cli/bpmetadata/types.go
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/1380
=> fix: Export dir for metadata and regenerate schema

infra/terraform/modules/repositories/main.tf
=> chore: fix repo permissions

infra/terraform/test-org/org/locals.tf
Resolves https://github.com/GoogleCloudPlatform/terraform-dynamic-python-webapp/commit/63a032322f0257b060b6b2e82aab9e3f76744041
=> fix: add torus-dpe as owners of terraform-dynamic-python-webapp

cli/Makefile, cli/bpmetadata/proto/bpmetadata_ui.proto, cli/bpmetadata/proto/bpmetadata_ui_ext.proto, cli/bpmetadata/schema/bpmetadataschema.json, cli/bpmetadata/types_ui.go, cli/bpmetadata/types_ui_ext.go
- changes ram from int to float
- makes gpu types a list
- add labels for network extensions
- adds missing types to external IP
- adds text validation for UI fields
=> feat: bpmetadata extentions for ui

infra/terraform/test-org/org/locals.tf
Related to: https://github.com/GoogleCloudPlatform/terraform-example-java-dynamic-point-of-sale/pull/10
=> chore: update path to exclude

infra/terraform/test-org/org/locals.tf
Added terraform-google-out-of-band-security to list of CFT modules.
=> chore: onboard out of band security

infra/terraform/test-org/org/locals.tf
=> chore: update analytics-lakehouse owners

infra/terraform/test-org/org/locals.tf
Added owner in dns, nat, router, log-export , vpn, vpc-sc
=> chore: added owner in modules: dns, nat, router, log-export , vpn, vpc-sc

infra/terraform/test-org/org/locals.tf
correct user name to be Github user name
=> fix: analytics-lakehouse owner

infra/terraform/test-org/org/locals.tf
From: https://github.com/GoogleCloudPlatform/terraform-google-secured-data-warehouse/blob/main/build/lint.cloudbuild.yaml
=> fix: update terraform-google-secured-data-warehouse lint

infra/blueprint-test/build/int.cloudbuild.yaml, infra/blueprint-test/examples/simple_krm_blueprint/pod.yaml, infra/blueprint-test/examples/simple_krm_blueprint/setters.yaml, infra/blueprint-test/pkg/kpt/kpt.go, infra/blueprint-test/pkg/krmt/krm.go, infra/blueprint-test/test/krm_simple_blueprint_test.go
=> fix: logging and TestKRMSimpleBlueprint timeout

.github/workflows/update-tooling.yml
Reverts GoogleCloudPlatform/cloud-foundation-toolkit#1757 since usage is only for developer tools/test
=> Revert "chore: update update-tooling.yml"

infra/terraform/test-org/org/locals.tf
=> chore: update SFB owners

infra/terraform/test-org/ci-triggers/outputs.tf, infra/terraform/test-org/org/github.tf, infra/terraform/test-org/org/locals.tf
Add new module for backup-dr components to CFT
=> feat: add backup-dr module

infra/terraform/test-org/org/locals.tf
Adding myself as codeowner for [Analytics Lakehouse JSS](https://github.com/GoogleCloudPlatform/terraform-google-analytics-lakehouse/tree/main)
cc @davenportjw
=> feat: update locals.tf to add bradmiro as analytics lakehouse codeowner

.github/workflows/update-tooling.yml
=> chore: update update-tooling.yml

infra/terraform/test-org/org/github.tf, infra/terraform/test-org/org/locals.tf
- add owner to terraform-google-bigquery for data_warehouse module work
=> chore: Update locals.tf

infra/terraform/modules/workflow_files/lint.yaml.tftpl, infra/terraform/test-org/org/locals.tf
Also onboards a new blueprint cc @bradmiro
=> chore: add mod swapper to lint workflow

.github/workflows/build-push-cft-devtools.yml
* use "latest" `gcloud`
* switch from deprecated `assignee` to `assignees `
=> chore: update build-push-cft-devtools.yml

.pre-commit-config.yaml, infra/terraform/test-org/github/resources/renovate.json
Fixes #2086
- Also update the linter
=> chore: renovate.json typo

infra/build/developer-tools/build/scripts/test_lint.sh
fixes https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/2060
Also simplified the lint script since we no longer use the GH bot + markdown integration.
=> feat: add module swapper to lint script

infra/terraform/test-org/ci-triggers/locals.tf, infra/terraform/test-org/org/locals.tf
* adds terraform-cloud-client-api as a managed repo
=> feat: add terraform-cloud-client-api

infra/terraform/test-org/org/locals.tf
Mapping can be confirmed in internal tools.
=> fix: use correct github account for sigje

cli/Makefile
I forgot to reset patch version - already cancelled release
=> chore: fix cli semver

infra/terraform/test-org/ci-triggers/locals.tf, infra/terraform/test-org/org/locals.tf
* JSS = Jump Start Solution
* JSS 11.1 = Large data sharing Java web app
* JSS 11.2 = Large data sharing Go web app
* Please see Google-internal reason for this pull-request: [b/323502337](http://b/323502337)
* Please see Google-internal documentation about the process: [cl/629480508](http://cl/629480508) (see staging URL in that CL)
=> chore: Offboard JSS 11.1 and 11.2

infra/terraform/test-org/test-cleanup/project.tf
Needed for https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/2350
=> chore(CI): enable SC and CAI APIs in cft-project-manager

infra/terraform/test-org/org/locals.tf
Replaces torus-dpe with team-egg
Adds @LukeSchlangen (b/352422098)
=> chore: Update codeowners for team-egg, dynamic JSS applications

infra/terraform/dev-org/dev-project-cleanup/cleanup.tf
=> chore: migrate dev project cleaner to GAR

CODEOWNERS
=> chore: add Abhishek to CLI owners

infra/blueprint-test/pkg/golden/golden.go
Add a goroutines max for `JSONPathEqs()`
=> fix(blueprint-test): add goroutines max

infra/terraform/test-org/github/protection.tf
Adds adc admin groups for tgm and gcp orgs
=> chore: add adc admin group
